config/routes.rb
Rails.application.routes.draw do

  # resources :comments
  # resources :posts
  # resources :records
  resources :records do
    collection do
      get :thirty_days
      get :sixty_days
    end
  end
  devise_for :users
  get "u/:username", to: "public#profile", constraints: { username: /[^\/]+/}, as: "profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "search", to: "records#search", as: "search"
  # get "business", to: "records#business", as: "business"

  get "terms", to: "records#terms", as: "terms"
  get "privacy", to: "records#privacy", as: "privacy"
  get "websiteprivacypage", to: "records#websiteprivacy", as: "websiteprivacy"
  get "home", to: "records#home", as: "home"
  get "vaccines", to: "records#vaccines", as: "vaccines"

  delete 'records/:id/picture', to: 'records#destroy_picture', as: 'picdestroy'

  get "users", to: "users#index", as:"users"
  get "business", to: "records#business", as: "business"


  resources :communities do
    resources :posts
  end



  resources :subscriptions
  resources :comments, only: [:create]
  post "post/vote", to: "votes#create"
  post "comment/votecomment", to: "votecomments#create"




  # authenticated :user do
  #   root 'records#new', as: :authenticated_poop
  # end
  root to: "records#routes", as: :authenticated_root
  # authenticated(:user) do
  #   root 'records#routes'
  # end
  root to: 'records#home'
  # root to: 'records#home'
  get "public", to: "public#index", as: "public"
end

app/views/shared/_footer.html.erb
<!-- <div id="footer">
© 2019 Neal Sutaria Product --> <!-- - <a href="TermsofUse.html">Terms of Use</a> -->
<!-- </div> -->

<div class="footer"> © 2025 MHBright  <div class = "terms"> <span class = "termspadding"> <%= link_to "Terms", terms_path %> </span>
<span class = "privacy"> <%= link_to "Privacy", privacy_path %> </span>
<span class = "websiteprivacy"> <%= link_to "Website Privacy", websiteprivacy_path %> </span> </div>
</div>

app/views/shared/_navbar.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

<% if user_signed_in? && current_user.business == false  %>
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

    <!-- <img src="https://res.cloudinary.com/neals/image/upload/v1547808069/logo1.png" alt="logo"> -->
    <%= image_tag "logo1.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- <a href="" class="navbar-wagon-item navbar-wagon-link"> Hello, <%= current_user.username %></a> -->
      <span class="navbar-wagon-item navbar-wagon-link"> <%= link_to "Health Forum", public_path%> </span>
      <span class="navbar-wagon-item navbar-wagon-link"> <%= link_to "New record", new_record_path %> </span>
      <%= link_to "Search for record(s)", search_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->


      <div class="navbar-wagon-item">
        <div class="dropdown">
         <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class = "pie">
              <%= link_to records_path do %>
              <i class="bi bi-person"></i>
                <%= t(".profile", default: "My records") %>
              <% end %>
            </li>
            <li class = "pie">
              <%= link_to edit_user_registration_path do %>
                <i class="bi bi-gear"></i> <%= t(".setting", default: "Settings") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="bi bi-person-dash"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>

          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>



    <% end %>
  </div>

 <% if user_signed_in?%>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li class = "pie">
              <%= link_to public_path do %>
                <i class="fa fa-users"></i> <%= t(".p", default: "Health Forum") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to new_record_path do %>
                <i class="fa fa-square"></i> <%= t(".p", default: "New record") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to search_path do %>
                <i class="fa fa-search"></i> <%= t(".p", default: "Search record(s)") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to records_path do %>
                <i class="fa fa-user"></i> <%= t(".p", default: "My records") %>
              <% end %>
            </li>
             <li class = "pie">
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t(".setting", default: "Settings") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-window-close"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>



<% else %>


 <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li class = "pie">
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user"></i>  <%= t(".sign_in", default: "Sign Up") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to new_user_session_path do %>
                <i class="fa fa-arrow-right"></i> <%= t(".p", default: "Log in") %>
              <% end %>
            </li>

      </ul>
    </div>
  </div>
</div>

<% end %>








<% elsif user_signed_in? && current_user.business == true%>
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

    <!-- <img src="https://res.cloudinary.com/neals/image/upload/v1547808069/logo1.png" alt="logo"> -->
    <%= image_tag "logo1.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- <a href="" class="navbar-wagon-item navbar-wagon-link"> Hello, <%= current_user.username %></a> -->
      <span class="navbar-wagon-item navbar-wagon-link"> Business User </span>


      <!-- Avatar with dropdown menu -->

      <div class="navbar-wagon-item">
        <div class="dropdown">
         <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-window-close"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>

          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

 <% if user_signed_in?%>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
             <li class = "pie">
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t(".setting", default: "Settings") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-window-close"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>



<% else %>


 <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li class = "pie">
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user"></i>  <%= t(".sign_in", default: "Sign Up") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to new_user_session_path do %>
                <i class="fa fa-arrow-right"></i> <%= t(".p", default: "Log in") %>
              <% end %>
            </li>


      </ul>
    </div>
  </div>
</div>

<% end %>

<% else %>

<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

    <!-- <img src="https://res.cloudinary.com/neals/image/upload/v1547808069/logo1.png" alt="logo"> -->
    <%= image_tag "logo1.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- <a href="" class="navbar-wagon-item navbar-wagon-link"> Hello, <%= current_user.username %></a> -->
      <span class="navbar-wagon-item navbar-wagon-link"> <%= link_to "New record", new_record_path %> </span>
      <%= link_to "Search for record(s)", search_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->

      <div class="navbar-wagon-item">
        <div class="dropdown">
         <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class = "pie">
              <%= link_to records_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My records") %>
              <% end %>
            </li>
            <li class = "pie">
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t(".setting", default: "Settings") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-window-close"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>

          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

 <% if user_signed_in?%>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li class = "pie">
              <%= link_to new_record_path do %>
                <i class="fa fa-square"></i> <%= t(".p", default: "New record") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to search_path do %>
                <i class="fa fa-search"></i> <%= t(".p", default: "Search record(s)") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to records_path do %>
                <i class="fa fa-user"></i> <%= t(".p", default: "My records") %>
              <% end %>
            </li>
             <li class = "pie">
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t(".setting", default: "Settings") %>
              <% end %>
            </li>

            <li class = "pie">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-window-close"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>



<% else %>


 <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li class = "pie">
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user"></i>  <%= t(".sign_in", default: "Sign Up") %>
              <% end %>
            </li>
        <li class = "pie">
              <%= link_to new_user_session_path do %>
                <i class="fa fa-arrow-right"></i> <%= t(".p", default: "Log in") %>
              <% end %>
            </li>


      </ul>
    </div>
  </div>
</div>

<% end %>
<% end %>